CREATE TABLE products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    discount_price DECIMAL(10, 2),
    stitch_count INT DEFAULT 0,
    width_mm DECIMAL(8, 2),
    height_mm DECIMAL(8, 2),
    color_count INT DEFAULT 1,
    stop_count INT DEFAULT 1,
    category_id BIGINT NOT NULL,
    designer_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    rejection_reason VARCHAR(500),
    is_featured BOOLEAN DEFAULT FALSE,
    downloads_count INT DEFAULT 0,
    view_count INT DEFAULT 0,
    rating_average DECIMAL(3, 2) DEFAULT 0.00,
    rating_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (designer_id) REFERENCES users(id),
    INDEX idx_products_slug (slug),
    INDEX idx_products_status (status),
    INDEX idx_products_category (category_id),
    INDEX idx_products_designer (designer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
